language: cpp
compiler: 
- gcc
before_install:
- if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew tap homebrew/versions; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew install gcc49; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew link --force --overwrite gcc49; fi
script: 
- if [ $TRAVIS_OS_NAME == linux ]; then ./build_parsnp_linux.sh; fi 
- if [ $TRAVIS_OS_NAME == osx ]; then ./build_parsnp_osx.sh; fi 
notifications:
  email:
    recipients:
      - treangent@nbacc.net
    on_success: change
    on_failure: change
os:
- linux
- osx
